# Generated by Django 5.1.7 on 2025-04-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_pessoa', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=100)),
                ('email', models.TextField(max_length=150)),
                ('endereco', models.TextField(max_length=100)),
                ('cidade', models.TextField(max_length=50)),
                ('cep', models.TextField(max_length=10)),
                ('num_cartao', models.TextField(max_length=50)),
                ('nome_cartao', models.TextField(max_length=100)),
                ('validade', models.TextField(max_length=20)),
                ('cvv', models.TextField(max_length=3)),
            ],
        ),
    ]
